#build stage
FROM golang:1.20-alpine3.16
WORKDIR /app
COPY . .
RUN apk add curl
RUN apk add make
RUN curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.2/migrate.linux-amd64.tar.gz | tar xvz 
RUN mv migrate /bin/
COPY ./app.env .
ENTRYPOINT [ "/app/dev-start.sh" ]