version: '3'

services:
  backend:
    container_name: backend-simple-bank
    build: 
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - app.env
    volumes:
      - .:/app
    command: make server
    depends_on:
      - db
  db:
    container_name: postgres-db
    image: 


